
name: Data Updater SBH SWK LBN PJY

on:
  push:
    paths:
      - '.github/workflows/data-updater-sbhswklbnpjy.yml'
      - 'data-scraper-v2alpha.py'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 1 * *'

jobs:
  script:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 2
      matrix:
        type: [condo, terrace, semid, bungalow]
        state: [sabah, sarawak, labuan, putrajaya]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Data scraping and export
      id: scrape
      run: python -u data-scraper-v2alpha.py -t ${{ matrix.type }} -s ${{ matrix.state }}
      continue-on-error: true
    - name: Commit & push data updates
      run: |
        git config --local user.name github-actions
        git config --local user.email "action@github.com"
        git pull
        git add data/*.csv
        git add md5hash/*.md5
        if [[ $(git diff-index --cached HEAD) ]]; then
          git commit -m "Monthly data update"
          git tag -a $(date "+v%Y%m%d%H%M%S") -m "Monthly data update"
          git push origin main --follow-tags
        fi
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
    - name: Check on failures
      if: steps.scrape.outcome != 'success'
      run: exit 1