
name: Data Updater

on:
  push:
    paths:
      - '.github/workflows/data-updater.yml'
      - 'data-scraper-v2alpha.py'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 1 * *'

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Data scraping and export
      run: python -u data-scraper-v2alpha.py
    - name: Commit & push data updates
      run: |
        git config --local user.name github-actions
        git config --local user.email "action@github.com"
        git pull
        git add data/*.csv
        if [[ $(git diff-index --cached HEAD) ]]; then
          git commit -m "Monthly data update"
          git tag -a `date "+v%Y%m%d"` -m "Monthly data update"
          git push origin main --follow-tags
        fi
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
    - name: File Existence
      uses: andstor/file-existence-action@v1.1.0
      with:
        files: "data/update-trigger.csv"
    - name: Check file exists
      if: steps.check_files.outputs.files_exists == 'true'
      uses: actions/github-script@v3
      with:
        script: core.setFailed('Scraping end prematurely!')
